from pathlib import Path

ROOT_DIRECTORY_PATH = Path("__file__").resolve().parent
IMAGES_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "imagens"
DATA_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "data"
RAW_DATA_DIRECTORY_PATH = DATA_DIRECTORY_PATH / "raw"
PROCESSED_DATA_DIRECTORY_PATH = DATA_DIRECTORY_PATH / "processed"
SCRIPTS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "scripts"
METRIC_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "metrics"
REPORTS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "reports"
MODELS_DIRECTORY_PATH = ROOT_DIRECTORY_PATH / "models"